included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - galere
  - galereTests
  - galereUITests
  
excluded: 
  - Pods
  - R.generated.swift
  - .build # Where Swift Package Manager checks out dependency sources

disabled_rules: # rule identifiers to exclude from running
  - file_length
  - line_length
  - nesting
  - identifier_name
  - discarded_notification_center_observer

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_random
  - operator_usage_whitespace
  - overridden_super_call
  - sorted_imports
  - toggle_bool

# parameterized rules are first parameterized as a warning level, then error level.
line_length: 
  warning: 200
  error: 300

function_body_length:
  warning: 200 # warning
  error: 300 # error

# they can set both implicitly with an array
type_body_length:
  warning: 500 # warning
  error: 400 # error

# or they can set both explicitly
file_length:
  warning: 400
  error: 1000
  # naming rules can set warnings/errors for min_length and max_length

# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 80
    error: 100
